@startuml Facade structure

package "Subsytem " #DDDDDD {
    Concrete1Subsytem <--Concrete2Subsytem
    Concrete2Subsytem <-- Concrete1Subsytem
    Concrete4Subsytem --> Concrete3Subsytem 
}



@enduml