@startuml Factory structure

skinparam class {
BackgroundColor lightGreen
BorderColor black

}

interface Product

class Factory{
    + {abstract} factoryMethod()
    + operation()
}

class ConcreteFactory{
    + {abstract} factoryMethod()
    
}

Product <|-- ConcreteProduct
ConcreteFactory <- ConcreteProduct
Factory <|-- ConcreteFactory


@enduml