@startuml  Strategy structure

skinparam class {
BackgroundColor #DDDDDD
BorderColor black
ArrowColor black
}


interface Strategy {
    execute (data)
}


Class Context{
    strategy
    setStrategy(strategy)
    methodRandom()
}

class ConcreteStrategy{
    execute (data)
    
}

Context <-- Client
Context o-right-> Strategy
Strategy <|.. ConcreteStrategy


@enduml